### PR TITLE
One line cheetah macros

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by bukzor** [comment]
lgtm. Please show that all unit tests pass.

**Comment by asottile** [comment]
One test failure, but this test is also failing in master

```
anthony@anthony-VirtualBox:~/git/cheetah$ python cheetah/Tests/Test.py
/home/anthony/git/cheetah/Cheetah/Compiler.py:1543: UserWarning:
You don't have the C version of NameMapper installed! I'm disabling Cheetah's useStackFrames option as it is painfully slow with the Python version of NameMapper. You should get a copy of Cheetah with the compiled C version of NameMapper.
  "\nYou don't have the C version of NameMapper installed! "
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E..........................................................................
======================================================================
ERROR: runTest (Cheetah.Tests.Regressions.Mantis_Issue_21_Regression_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anthony/git/cheetah/Cheetah/Tests/Regressions.py", line 168, in runTest
    assert template.testMethod(output='bug') # raises a NameError: global name '_filter' is not defined
  File "cheetah_DynamicallyCompiledCheetahTemplate_1343493355_32_19264.py", line 98, in testMethod
NameError: global name 'self' is not defined

----------------------------------------------------------------------
Ran 2153 tests in 24.155s

FAILED (errors=1)
```

**Comment by asottile** [comment]
Here's my branch:

```
anthony@anthony-VirtualBox:~/git/cheetah$ git checkout one_line_cheetah_macros
Switched to branch 'one_line_cheetah_macros'

anthony@anthony-VirtualBox:~/git/cheetah$ python cheetah/Tests/Test.py
/home/anthony/git/cheetah/Cheetah/Compiler.py:1543: UserWarning:
You don't have the C version of NameMapper installed! I'm disabling Cheetah's useStackFrames option as it is painfully slow with the Python version of NameMapper. You should get a copy of Cheetah with the compiled C version of NameMapper.
  "\nYou don't have the C version of NameMapper installed! "
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E..........................................................................

======================================================================
ERROR: runTest (Cheetah.Tests.Regressions.Mantis_Issue_21_Regression_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anthony/git/cheetah/Cheetah/Tests/Regressions.py", line 168, in runTest
    assert template.testMethod(output='bug') # raises a NameError: global name '_filter' is not defined
  File "cheetah_DynamicallyCompiledCheetahTemplate_1343493660_7_66843.py", line 98, in testMethod

NameError: global name 'self' is not defined

----------------------------------------------------------------------
Ran 2165 tests in 26.395s

FAILED (errors=1)
```

**Comment by bukzor** [comment]
We'll hold on this till we confirm that we need it.

**Comment by eevee** [comment]
Even if partials use a macro, this seems extremely unnecessary.  Just make the contents empty.

Using the full existing syntax allows extending the idea to something like #call later, too.

**Comment by asottile** [comment]
It's the difference between:

#partial partials.business.small, $business

and

#partial partials.business.small, $business: ;

or

#partial partials.business.small, $business
#end partial

**Comment by asottile** [comment]
Won't fix

**Pull request closed without merging**
