### PR TITLE
Fix whitespace

### PR DESCRIPTION
**Pull request by bukzor**
Get these trivial changes out of the way so they don't obscure my functional patches.

### CODE REVIEW

**Comment by bukzor** [comment]
Ran 2138 tests in 29.049s

OK

**Comment by dnephin** [comment]
I approve

**Comment by smoy** [comment]
I appove

**Comment by smoy** [comment]
Since we are not proceeding with the whitespace change, should we close this pull request?

**Comment by bukzor** [comment]
Yes. I'm withdrawing it.

**Pull request closed without merging**
